services:
    simpleapi:
        build: ./api/simpleapi
        networks:
          - proxy-net
          - db-net
        depends_on:
          database:
            condition: service_healthy
        healthcheck:
          test: ["CMD", "curl", "-f", "http://localhost:8080"]
          interval: 10s
          retries: 5
          start_period: 30s
          timeout: 10s
        environment:
          - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
          - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
          - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
          - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=${SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT}

    database:
        build: ./database
        networks:
          - db-net
        volumes:
          - type: bind
            source: ./postgres_data
            target: /var/lib/postgresql/data/
        environment:
          - POSTGRES_USER=${POSTGRES_USER}
          - POSTGRES_DB=${POSTGRES_DB}
        healthcheck:
          test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
          interval: 10s
          retries: 5
          start_period: 30s
          timeout: 10s

    http:
        build: ./http
        ports:
          - 9000:80
        networks:
          - proxy-net
        depends_on:
          simpleapi:
            condition: service_healthy

networks:
  proxy-net:
  db-net:
